### PR TITLE
Add bootstrap/conda setup scripts

### PR DESCRIPTION
**Pull request by koverholt**
Sets up environment on EC2 (tested with Ubuntu 14.04, ami-d05e75b8), including:
- Miniconda/Python
- git repo
- unzips data
- installs and sets up Postgres
- runs `create_postgres_dts.py`

### CODE REVIEW

**Comment by koverholt** [comment]
This is ready to be merged, and helps to quickly reproduce the working environment on a clean EC2 instance. Currently, it gets to this point:

```
python data_setup/create_postgres_dts.py makefiles/year_list.pkl
```

Then we can talk more about where to go from here.

**Comment by sallamander** [comment]
Kris,

Does it fail past that point?

Sean

**Comment by koverholt** [comment]
Nope, it looks like it loads the data successfully. I just didn't know what the next step was. :)

**Comment by sallamander** [comment]
Kris,

Okay, great. I'll look this over before we chat tomorrow and we can go from
there.

Thanks!
Sean

**Comment by koverholt** [comment]
Can you merge this PR? Or do you want to hold off until we chat?

The only thing that might affect the code on your side is the addition to `forest-fires/code/data_setup/create_postgres_dts.py`, specifically, `host='/var/run/postgresql'` on [this line](https://github.com/koverholt/forest-fires/blob/ec2-bootstrap/code/data_setup/create_postgres_dts.py#L86). This may or may not work on your local machine depending on how you are running Postgres.

**Comment by sallamander** [comment]
Kris,

I want to hold off both until we chat and I chat with my instructor. I need
to talk with him about logistics and specifics about how the project is
supposed to work.

Sean

**Comment by koverholt** [comment]
Gotcha, look forward to talking more tomorrow.

**Pull request closed without merging**
